DATASET_ROOT: "../bdataset"
JSON_PATH: "train1.json"
BATCH_SIZE: 2
IMAGE_SIZE: 256
WORKERS: 8
PIN_MEMORY: True
SHUFFLE: True

LEARNING_RATE: 0.01
BETAS: [0.9, 0.999]
EPS: 0.00000001
MOMENTUM: 0.9
DAMPENING: 0.1
WEIGHT_DECAY: 0.0001

MILESTONES: [5,10,15]
GAMMA: 0.2

NUM_EPOCHS: 20
TEST: False
OUT_PATH: "./runs"
LOAD_MODEL: False
SAVE_MODEL: True
CHECKPOINT_FILE: "normal.pth"