DATASET_ROOT: "../bdataset_segmentation"
JSON_PATH: "test.json"
BATCH_SIZE: 16
IMAGE_SIZE: 256
WORKERS: 8
PIN_MEMORY: True
SHUFFLE: True

LEARNING_RATE: 0.0001
BETAS: [0.9, 0.999]
EPS: 0.00000001
WEIGHT_DECAY: 0.0001

MILESTONES: [50, 100, 200]
GAMMA: 0.2

NUM_EPOCHS: 50
TEST: False
OUT_PATH: "./runs"
LOAD_MODEL: False
SAVE_MODEL: False
CHECKPOINT_FILE: "normal.pth"
